version: '3.7'
services:
  backend:
    container_name: dental-backend
    build:
      context: ./backend
    ports:
      - '${DEVELOPMENT_BACKEND_PORT}:${DEVELOPMENT_BACKEND_PORT}'
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/backend
      - /backend/node_modules
  frontend:
    container_name: dental-frontend
    build:
      context: ./frontend
    ports:
      - '${DEVELOPMENT_FRONTEND_PORT}:${DEVELOPMENT_FRONTEND_PORT}'
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
