# fly.toml app configuration file generated for dental-notetaker on 2024-03-16T15:10:15+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dental-notetaker'
primary_region = 'syd'

[build]

[[services]]  
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
